ci: validate github secret

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,5 +32,16 @@ jobs:
       - name: Install Dependencies
         run: npm ci
 
+      - name: Check Secret Exists
+        env:
+          API_KEY: ${{ secrets.API_KEY }}
+        run: |
+          if [ -z "$API_KEY" ]; then
+            echo "Secret is missing"
+            exit 1
+          else
+            echo "API_KEY secret exists"
+          fi
+
       - name: Run Tests
         run: npx jest
